### ISSUE TITLE
max in `RNG::generate_range()` is exclusive but docs suggest otherwise

### ISSUE THREAD

**Issue by kyoobey** [inspier/picorand#1]
this is the example provided for https://docs.rs/picorand/latest/picorand/struct.RNG.html#method.generate_range
```rs
use picorand::{WyRand, RNG};
let mut rng = RNG::<WyRand, u8>::new(0xDEADBEEF);
let generated = rng.generate_range(0xC0, 0xDE);
assert!(generated >= 0xC0 || generated <= 0xDE);
```

`generated` is never equal to `0xDE`, so the correct code should be:
```rs
assert!(generated >= 0xC0 || generated < 0xDE);
```

or am i missing something and this is actually a bug ?

**Comment by inspier** [comment]
Fixed in: [88068a7](https://github.com/inspier/picorand/commit/88068a7e46dd27dcb73f2c256a011c6113f920b2), good catch and thanks.
